### ISSUE TITLE
Installation Package for Linux(.deb/.rpm) and Windows(.exe)

### ISSUE THREAD

**Issue by arashifunsho** [abdularis/LAN-Share#2]
First, I want to say thank you for the awesome project. I got to know about it when it was featured in the Linux Format Magazine (LXF230 Issue, November 2017); I've always wanted a tool like this to share files within my office, but not via the Internet like we currently do.

So, It would really be helpful if you can generate an installation package to enable less tech-savvy end users install and use the application.

Thanks in advance

**Comment by abdularis** [comment]
Thank you for using this tools and i'am sorry for late response.
actually i've built the installation package (.deb debian/ubuntu) and .exe for windows PC, you can check this out at the release page [https://github.com/abdularis/LAN-Share/releases](url), currently I've built this just for 64bit.
in ubuntu you can install it using dpkg:
$ sudo dpkg -i ./file_name.deb
