### ISSUE TITLE
Linux-Windows communication not working

### ISSUE THREAD

**Issue by Tsftsf** [abdularis/LAN-Share#21]
Installed LANshare on both WIN10 and Linux-Mint 19. From Windows to Linux I have no problem sending files. From Linux to windows I can not do it. There is a yellow "waiting" in the staus window that won't go away. I'm trying to send to a Public folder in windows that has sharing permission, so that's not the problem. What else can it be?

**Comment by Tsftsf** [comment]
Solved my own problem. Have to add and enable "LANshare.exe" in Windows firewall.

**Comment by gizmouk** [comment]
Hi - I had the same issue with Linux Mint 19 to Linux Mint 19. Working now but I can only share the system disk.... I have second disks for data on each PC, how can I share those too?

**Comment by gustavklopp** [comment]
Same problem: From Arch Linux to Windows 10. I've enabled the exe program in Windows defender but to no avail. Still "Waiting".

**Comment by Ajay-Raj-S** [comment]
Sender - Windows 10, Reciever - Ubuntu 18.04
Disabling the firewall on the recieving machine solved my issue,
