### ISSUE TITLE
Auto Updater for AppImage releases

### ISSUE THREAD

**Issue by antony-jr** [abdularis/LAN-Share#29]
It would it be nice to see LANShare use AppImage update to auto update itself. You can use [AppImageUpdaterBridge](https://antony-jr.github.io/AppImageUpdaterBridge) to delta update your AppImage(self-update). The library is written in C++ using Qt5 so this does not add extra dependencies. I already made the required changes in [my fork](https://github.com/antony-jr/LAN-Share) which also has an **AppImage built in the releases**. Here is how it looks like.... (If you would like , I could just open PR from my fork)

**Note** : The update is pretty fast since only the deltas are downloaded and else is fetched from the old file.

![Screenshot_20190503_235532](https://user-images.githubusercontent.com/33930174/57157700-16e97f00-6dff-11e9-8d30-3f2744c95d97.png)

![Screenshot_20190503_235545](https://user-images.githubusercontent.com/33930174/57157717-21a41400-6dff-11e9-8b4d-381c154c95a9.png)

![Screenshot_20190503_235556](https://user-images.githubusercontent.com/33930174/57157724-27015e80-6dff-11e9-91c3-ae15d792cff6.png)

**Comment by cstayyab** [comment]
I was about to request for an AppImage here. Superb. A PR would be really nice.

**Comment by antony-jr** [comment]
> I was about to request for an AppImage here. 

@cstayyab  LANShare already has an AppImage , get it from the releases.
