### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [abdularis/LAN-Share#5]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

I'm happy to help making an AppImage if you are interested.

**Comment by abdularis** [comment]
Sure thank you
It would be great if we have an appimage package, it's instant & easier to use

**Comment by probonopd** [comment]
Please let me know if you are running into issues making the AppImage or gathering the required information, so that I can help you.

**Comment by abdularis** [comment]
I have no experience working with appimage before, so i think i have to go from scratch

**Comment by probonopd** [comment]
Let me see what I can do real quick...

**Comment by probonopd** [comment]
A test AppImage is available at https://github.com/probonopd/LAN-Share/releases. Please let me know how it works for you. Then I will send a pull request.

**Comment by michaldybczak** [comment]
I downloaded appimage and as far as the program launch goes, it works :). Haven't tested file transfer yet.
It looks nice, clean and easy:

![screenshot_20180531_213616](https://user-images.githubusercontent.com/10132958/40804108-a8cfdae8-651a-11e8-82cd-70ef2bab6fda.jpg)

**Comment by probonopd** [comment]
> Haven't tested file transfer yet.

Can you do this please so that we know it actually works? Thanks.

**Comment by abdularis** [comment]
the appimage works perfectly
I've tested file transfer on two laptop connected through local wifi network and it works fine, how about you

**Comment by thecursedfly** [comment]
I tried the appimage and for me file transfer does not work, or not completely.
I am able to transfer files from a Windows 7 PC to my Fedora PC, but not the other way around; the Windows PC is not detected and not available for selection when it scans for other machines.
Any idea what could be the issue, if related to the appimage or something else? I cannot test the application in other ways as no rpm is available.

**Comment by abdularis** [comment]
@thecursedfly make sure those two pc can ping each other, & please check the windows firewall to allow the application to send & receive packet from network

**Comment by abdularis** [comment]
I've run it on windows 10 and xubuntu 14.04, allow any udp and/or tcp port (in/out) in windows firewall settings

![desktop 1_08 07 58](https://user-images.githubusercontent.com/22021261/40869029-68544b96-663e-11e8-9f2d-8d433c30756b.png)

![capture](https://user-images.githubusercontent.com/22021261/40869032-79052a00-663e-11e8-989f-ac3d68df1fb7.PNG)

**Comment by probonopd** [comment]
@thecursedfly does it work on the same system with the non-AppImage version?

**Comment by thecursedfly** [comment]
My system is Fedora and there is no rpm; and I'm not expert enough to build from source.

I disabled the firewall in Windows and from Linux I can ping the Windows machine; still, not able to detect the Windows machine in LANShare.

**Comment by thecursedfly** [comment]
I can also ping the Linux PC from Windows

**Comment by michaldybczak** [comment]
I launched LAN Share from appimage on Manjaro (firewall off) and from deb on old Elementary OS. At first list of detected OSes was empty but then it detected the other system and transferred files correctly without a hassle.
Will have test it more with Windows systems, so far so good :).

**Comment by michaldybczak** [comment]
I tested it at work between Manjaro laptop (appimage) and Windows 10 PC (installed), works correctly in both ways 👍 . If firewall is not blocking ports all works well. Super easy, no need to read hours about servers and set one up.

One small thing I would like see is: when waiting for the other system to show up, I should see some progress bar/working circle/scanning/searching... etc. anything indicating that program is working and I just need to wait a little. There is some small delay (1-3s) before system shows up and in that time a user feels insecure if it's working, so indication that it does something would be nice. It's good for first impressions and overall feeling on how program works.

Although I could possibly set a NAS server I prefer to use such program. It's awesome in its simplicity!

**Comment by thecursedfly** [comment]
I can finally confirm that it works also for me under Fedora 28 for transferring to and from Windows after I added the two ports (both tcp and udp) to the Fedora firewall. I was previously trying to disable the firewall, but it seems I was not having success.
Works great, thanks.

**Comment by abdularis** [comment]
So the AppImage is really works
close the issue
